[package]
name = "interstellar"
version = "1.0.0"
description = "InterStellar Secure Decentralized Mesh Messenger & AI Defense"
authors = ["Reiclid"]
edition = "2021"

[lib]
name = "interstellar"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-rc", features = [] }

[dependencies]
tauri = { version = "2.0.0-rc", features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
